/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChercheursRouteImport } from './routes/chercheurs'
import { Route as BailleursRouteImport } from './routes/bailleurs'
import { Route as AxesRouteImport } from './routes/axes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChercheursIdRouteImport } from './routes/chercheurs.$id'

const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChercheursRoute = ChercheursRouteImport.update({
  id: '/chercheurs',
  path: '/chercheurs',
  getParentRoute: () => rootRouteImport,
} as any)
const BailleursRoute = BailleursRouteImport.update({
  id: '/bailleurs',
  path: '/bailleurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AxesRoute = AxesRouteImport.update({
  id: '/axes',
  path: '/axes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChercheursIdRoute = ChercheursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChercheursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/axes': typeof AxesRoute
  '/bailleurs': typeof BailleursRoute
  '/chercheurs': typeof ChercheursRouteWithChildren
  '/contact': typeof ContactRoute
  '/datasets': typeof DatasetsRoute
  '/evenements': typeof EvenementsRoute
  '/formations': typeof FormationsRoute
  '/login': typeof LoginRoute
  '/partenaires': typeof PartenairesRoute
  '/profil': typeof ProfilRoute
  '/projets': typeof ProjetsRoute
  '/publications': typeof PublicationsRoute
  '/recherche': typeof RechercheRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ressources': typeof RessourcesRoute
  '/chercheurs/$id': typeof ChercheursIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/axes': typeof AxesRoute
  '/bailleurs': typeof BailleursRoute
  '/chercheurs': typeof ChercheursRouteWithChildren
  '/contact': typeof ContactRoute
  '/datasets': typeof DatasetsRoute
  '/evenements': typeof EvenementsRoute
  '/formations': typeof FormationsRoute
  '/login': typeof LoginRoute
  '/partenaires': typeof PartenairesRoute
  '/profil': typeof ProfilRoute
  '/projets': typeof ProjetsRoute
  '/publications': typeof PublicationsRoute
  '/recherche': typeof RechercheRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ressources': typeof RessourcesRoute
  '/chercheurs/$id': typeof ChercheursIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/axes': typeof AxesRoute
  '/bailleurs': typeof BailleursRoute
  '/chercheurs': typeof ChercheursRouteWithChildren
  '/contact': typeof ContactRoute
  '/datasets': typeof DatasetsRoute
  '/evenements': typeof EvenementsRoute
  '/formations': typeof FormationsRoute
  '/login': typeof LoginRoute
  '/partenaires': typeof PartenairesRoute
  '/profil': typeof ProfilRoute
  '/projets': typeof ProjetsRoute
  '/publications': typeof PublicationsRoute
  '/recherche': typeof RechercheRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ressources': typeof RessourcesRoute
  '/chercheurs/$id': typeof ChercheursIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/auth'
    | '/axes'
    | '/bailleurs'
    | '/chercheurs'
    | '/contact'
    | '/datasets'
    | '/evenements'
    | '/formations'
    | '/login'
    | '/partenaires'
    | '/profil'
    | '/projets'
    | '/publications'
    | '/recherche'
    | '/reset-password'
    | '/ressources'
    | '/chercheurs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/auth'
    | '/axes'
    | '/bailleurs'
    | '/chercheurs'
    | '/contact'
    | '/datasets'
    | '/evenements'
    | '/formations'
    | '/login'
    | '/partenaires'
    | '/profil'
    | '/projets'
    | '/publications'
    | '/recherche'
    | '/reset-password'
    | '/ressources'
    | '/chercheurs/$id'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/auth'
    | '/axes'
    | '/bailleurs'
    | '/chercheurs'
    | '/contact'
    | '/datasets'
    | '/evenements'
    | '/formations'
    | '/login'
    | '/partenaires'
    | '/profil'
    | '/projets'
    | '/publications'
    | '/recherche'
    | '/reset-password'
    | '/ressources'
    | '/chercheurs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  AuthRoute: typeof AuthRoute
  AxesRoute: typeof AxesRoute
  BailleursRoute: typeof BailleursRoute
  ChercheursRoute: typeof ChercheursRouteWithChildren
  ContactRoute: typeof ContactRoute
  DatasetsRoute: typeof DatasetsRoute
  EvenementsRoute: typeof EvenementsRoute
  FormationsRoute: typeof FormationsRoute
  LoginRoute: typeof LoginRoute
  PartenairesRoute: typeof PartenairesRoute
  ProfilRoute: typeof ProfilRoute
  ProjetsRoute: typeof ProjetsRoute
  PublicationsRoute: typeof PublicationsRoute
  RechercheRoute: typeof RechercheRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RessourcesRoute: typeof RessourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chercheurs': {
      id: '/chercheurs'
      path: '/chercheurs'
      fullPath: '/chercheurs'
      preLoaderRoute: typeof ChercheursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bailleurs': {
      id: '/bailleurs'
      path: '/bailleurs'
      fullPath: '/bailleurs'
      preLoaderRoute: typeof BailleursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/axes': {
      id: '/axes'
      path: '/axes'
      fullPath: '/axes'
      preLoaderRoute: typeof AxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chercheurs/$id': {
      id: '/chercheurs/$id'
      path: '/$id'
      fullPath: '/chercheurs/$id'
      preLoaderRoute: typeof ChercheursIdRouteImport
      parentRoute: typeof ChercheursRoute
    }
  }
}

interface ChercheursRouteChildren {
  ChercheursIdRoute: typeof ChercheursIdRoute
}

const ChercheursRouteChildren: ChercheursRouteChildren = {
  ChercheursIdRoute: ChercheursIdRoute,
}

const ChercheursRouteWithChildren = ChercheursRoute._addFileChildren(
  ChercheursRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  AuthRoute: AuthRoute,
  AxesRoute: AxesRoute,
  BailleursRoute: BailleursRoute,
  ChercheursRoute: ChercheursRouteWithChildren,
  ContactRoute: ContactRoute,
  DatasetsRoute: DatasetsRoute,
  EvenementsRoute: EvenementsRoute,
  FormationsRoute: FormationsRoute,
  LoginRoute: LoginRoute,
  PartenairesRoute: PartenairesRoute,
  ProfilRoute: ProfilRoute,
  ProjetsRoute: ProjetsRoute,
  PublicationsRoute: PublicationsRoute,
  RechercheRoute: RechercheRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RessourcesRoute: RessourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
